version: "3"
services:
  projectname-app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${APP_PORT:-18000}:8000
    volumes:
      - ${PROJECT_PATH:-./src}:/work/${COMPOSE_PROJECT_NAME}:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work/${COMPOSE_PROJECT_NAME}
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=projectname-db
      - DB_DATABASE=${DB_NAME:-homestead}
      - DB_USERNAME=${DB_USER:-homestead}
      - DB_PASSWORD=${DB_PASS:-secret}
      - TZ=${TZ:-Asia/Tokyo}

  projectname-nginx:
    image: nginx:alpine
    depends_on:
      - projectname-app
    ports:
      - ${WEB_PORT:-10091}:8086
    volumes:
      - ${PROJECT_PATH:-./src}:/work/${COMPOSE_PROJECT_NAME}:delegated
      - ./docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: /bin/sh -c "envsubst '$$COMPOSE_PROJECT_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  projectname-db:
    image: mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME:-homestead}
      - MYSQL_USER=${DB_USER:-homestead}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${DB_PORT:-13311}:3306

  projectname-redis:
    image: redis:alpine
    volumes:
      - redis-store:/data

volumes:
  db-store:
    driver: local
  redis-store:
    driver: local
