version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ:-Asia/Tokyo}
    volumes:
      - ${PROJECT_PATH:-./src}:/work/${COMPOSE_PROJECT_NAME}:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work/${COMPOSE_PROJECT_NAME}
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE:-homestead}
      - DB_USERNAME=${DB_USERNAME:-homestead}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - TZ=${TZ:-Asia/Tokyo}

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-10091}:8086
    volumes:
      - ${PROJECT_PATH:-./src}:/work/${COMPOSE_PROJECT_NAME}:delegated
      - ./docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: /bin/sh -c "envsubst '$$COMPOSE_PROJECT_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: mysql:8.0
    volumes:
      - ./docker/logs:/var/log/mysql
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-homestead}
      - MYSQL_USER=${DB_USERNAME:-homestead}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${DB_PORT:-13311}:3306

  redis:
    image: redis:alpine

volumes:
  db-store:
    driver: local
